language: node_js
node_js:
  - '12.10.0'
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install
script:
  - "npm run lint"
  - "npm run build"
after_success:
  - npm run coverage
